#pragma config(Motor,  port2,           rightWheel,    tmotorVex269, openLoop)
#pragma config(Motor,  port3,           leftWheel,     tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port4,           rotateClaw,     tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*
	Power Levels:
	127 = Full power forward
	-127 = Full power backwards
	0 = Stationary
	Commands:
	vexRT[] refers to the Vex Joystick's buttons/joysticks
	#pragmas refer to the ports
	*/
	
	//The while loop will play the program ALWAYS, this is continous to check the joystick's position, if a button is pressed, etc.
	while(1 == 1)
	{ 
		
	motor[rightWheel] = vexRT[Ch2]; //The vexRT[Ch2] refers to Channel 2's joystick (127 = up, -127  down, 0 = stationary)
	motor[leftWheel] = vexRT[Ch3]; //The vexRT[Ch3] refers to Channel 3's joystick (127 = up, -127 down, 0 = stationary)
		
	/* Channel 6 Buttons UP and DOWN*/
	if (vexRT[Btn6U] == 1) //UP Pressed
	{
	motor[rotateClaw] = 127; //Full power rotation
	wait1Msec(2000); //Play for 2 seconds
	motor[rotateClaw] = 0; //Then stop
	} else if (vexRT[Btn6D] == 1) //DOWN Pressed
	{
	motor[rotateClaw] = -127; //Full power opposite rotation
	wait1Msec(2000); //Play for 2 seconds
	motor[rotateClaw] = 0; //Then stop
		
	} 		
}
