#pragma config(Motor,  port2,           rightWheel,    tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port3,           leftWheel,     tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*
	You can lower the powers for the motors to make the robot move slower.
	If you want the motors to go backwards, then you can make the powers negatives.
	If you want the robot to turn to the right, make the right motor power negative and left motor power positive.
	If you want the robot to turn to the left, make the right motor power positive and left motor power negative.
	rightWheel/rightMotor = Port 2, Inversed/Reversed
	leftWheel/leftMotor = Port 3, Normal
	vexRt[Ch#] refers to the motor power
	*/

	while(true)
	{ //The while loop will play the program ALWAYS, this is continous to check the joystick's position, if a button is pressed, etc.
	motor[rightWheel] = vexRT[Ch2]; //The vexRT[Ch2] refers to Channel 2's joystick (127 = up, -127  down, 0 = stationary)
	motor[leftWheel] = vexRT[Ch3]; //The vexRT[Ch3] refers to Channel 3's joystick (127 = up, -127 down, 0 = stationary)
	}
}
